# Generated by Django 5.2.6 on 2025-10-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
